### ISSUE TITLE
Replace Vimeo with Archive.org

### ISSUE THREAD

**Issue by lmuzinic** [zgphp/zgphp-sculpin#16]
ZgPHP moved all videos from Vimeo to Archive.org and would like to reflect those changes on [zgphp.org](https://zgphp.org) as well. To do that, all video posts in this repo need to be updated with new identifiers/slugs.

Updates needed:
- drop vimeo_id param
- drop image param
- add archive_id param with its identifier

Archive.org video identifier can be found on video page. [Example video](https://archive.org/details/ZgPHPDanielLeechComparativeBenchmarkingWithPHPBench).

[List of all ZgPHP videos on archive.org](https://archive.org/search.php?query=mediatype%3A%28movies%29%20AND%20subject%3A%28zgphp%29)

[Example of modifications](https://github.com/zgphp/zgphp-sculpin/commit/680199fa91d427a21a99599ac50c7578157f8c86) needed on [all videos](https://github.com/zgphp/zgphp-sculpin/tree/master/source/_videos).

**Comment by traseta** [comment]
Why not YouTube? :)
